name: auto-format
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: chekout
        uses: actions/checkout@v2
      - name: show branches
        run: echo "from:${{ github.head_ref }} to:${{ github.base_ref }}"
      - name: format
        run: |
          ./gradlew ktlintFormat
      - name: detect diff
        id: diff
        run: |
          diff=$(git diff)
          test -n $diff && change="found" || change="none"
          echo "::set-output name=change::$change"
      - name: debug
        if: steps.diff.outputs.change == 'found'
        run: |
          echo "change"
      - name: create PR
        if: steps.diff.outputs.change == 'hoge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub push
          hub pull-request -b ${{ github.base_ref }} -m "ktlint format"
