name: auto-format
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.head_ref != 'feature/format'
    steps:
      - name: chekout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: show branches
        run: echo "from:${{ github.head_ref }} to:${{ github.base_ref }}"
      - name: format
        run: |
          ./gradlew ktlintFormat
      - name: detect diff
        id: diff
        run: |
          git diff
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: check remote branch
        id: remote_branch
        run: |
          git ls-remote --heads https://github.com/${{ github.repository }}.git
          exist=$(git ls-remote --heads https://github.com/${{ github.repository }}.git |
            grep feature/format | wc -l)
          echo "::set-output name=exists::$exists"
      - name: update PR
        if: steps.diff.outputs.count > 0 && steps.remote_branch.outputs.exists == 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git branch feature/format
          git checkout feature/format
          git add .
          git commit -m "ktlint format"
          git push --force origin feature/format
      - name: create PR
        if: steps.diff.outputs.count > 0 && steps.remote_branch.outputs.exists == 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git branch feature/format
          git checkout feature/format
          git add .
          git commit -m "ktlint format"
          git push --set-upstream --force origin feature/format
          hub pull-request -b ${{ github.base_ref }} -m "Auto Format

          This PR contains formatted codes by KtLint.
          - [ktlint](https://github.com/pinterest/ktlint)
          - [ktlint-gradle](https://github.com/jlleitschuh/ktlint-gradle)"
