name: auto-format
on:
  pull_request:
    types:
      - closed
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_target: ${{ steps.check.outputs.is_target }}
    steps:
      - name: Determine default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "default_branch_ref=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV
      - name: Debug
        run: echo ${{ env.default_branch }}
      - id: ckeck
        name: Check whether or not to run formatter
        run: echo "::set-output name=is_target::${{
            github.base_ref == env.default_branch_ref &&
            github.event.pull_request.merged
          }}"
  format:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.is_target
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: echo ${{ needs.check.outputs.is_target }}
      - name: Deploy
        if: github.base_ref == env.default_branch_ref
        run: echo "Run!"