name: auto-format
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: chekout
        uses: actions/checkout@v2
      - name: show branches
        run: echo "from:${{ github.head_ref }} to:${{ github.base_ref }}"
      - name: format
        run: |
          ./gradlew ktlintFormat
      - name: detect diff
        id: diff
        run: |
          git diff
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: create PR
        if: steps.diff.outputs.count > 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git branch feature/format
          git checkout feature/format
          git add .
          git commit -m "ktlint format"
          hub push
          hub pull-request -b ${{ github.base_ref }} -m "Auto Format"
