name: auto-format
on:
  pull_request:
    branches:
      - main
    types:
      - closed
env:
  GRADLE_KTLINT_TASK: 'ktlintFormat'
  NDK_VERSION: 21.3.6528147
jobs:
  format:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && !startsWith(github.head_ref, 'feature/format')
    steps:
      - name: chekout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: debug
        run: ls -l /usr/local/lib/android/sdk/ndk
      - name: restore NDK cache
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
          key: ${{ runner.os }}-ndk-${{ env.NDK_VERSION }}-v3
      - name: setup NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: |
          ${ANDROID_HOME}/tools/bin/sdkmanager \
            --install "ndk;${NDK_VERSION}" \
            --sdk_root=${ANDROID_SDK_ROOT}
      - name: debug
        run: ls -l /usr/local/lib/android/sdk/ndk
      - name: restore gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
      - name: format
        run: ./gradlew $GRADLE_KTLINT_TASK
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: ktlint format
          branch: feature/format
          branch-suffix: short-commit-hash # 同じプルリクは作らない
          base: ${{ github.base_ref }}
          title: Auto format with ktlint
          body: |
            Automated changes by [${{ github.workflow }}](https://github.com/${{ github
            .repository }}/actions/runs/${{ github.run_id }})
