name: auto-format
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: echo "from:${{ github.head_ref }} to:${{ github.base_ref }}"