name: auto-format
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !startsWith(github.head_ref, 'feature/format')
    steps:
      - name: chekout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: show branches
        run: echo "from:${{ github.head_ref }} to:${{ github.base_ref }}"
      - name: format
        run: |
          ./gradlew ktlintFormat
      - name: detect diff
        id: diff
        run: |
          git diff
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: create PR
        if: steps.diff.outputs.count > 0
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: ktlint format
          branch: feature/format
          branch-suffix: short-commit-hash # 同じプルリクは作らない
          base: ${{ github.base_ref }}
          title: Auto format with ktlint
          body: |
            Automated changes by [${{ github.workflow }}](https://github.com/${{ github
            .repository }}/actions/runs/${{ github.run_id }}) with [create-pull-request]
            (https://github.com/peter-evans/create-pull-request) GitHub action.
